CREATE OR REPLACE FUNCTION "UDF_BUILDNETWORK"(
    "PNAME" VARCHAR(16777216)
    , "PID" VARCHAR
    , "CNAME" VARCHAR(16777216)
    , "CID" VARCHAR)
RETURNS TABLE ("PROVIDERNAME" VARCHAR(16777216), "PROVIDERID" VARCHAR
    , "CONSUMERNAME" VARCHAR(16777216)
    , "CONSUMERID" VARCHAR
    , "PROVIDERX" FLOAT, "PROVIDERY" FLOAT
    , "CONSUMERX" FLOAT
    , "CONSUMERY" FLOAT)
LANGUAGE JAVA
HANDLER = 'NetworkBuilder.buildNetwork'
IMPORTS = ('@DATACLOUD.PUBLIC.JARS/DataCloudToolkit.jar');